routes/web.php
<?php

use App\Http\Controllers\BlogsController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProduksController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\JasaPengirimanController;
use App\Http\Controllers\VouchersController;
use App\Http\Controllers\OrdersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['auth']], function () {
    Route::prefix('admin')->group(function () {
        Route::get('/get-penjualan', [App\Http\Controllers\DashboardAdminController::class, 'getPenjualan'])->name('get-penjualan');
        Route::get('/get-penjualan-bulan', [App\Http\Controllers\DashboardAdminController::class, 'getPenjualanBulan'])->name('get-penjualan-bulan');
        Route::resource('/dashboard', DashboardAdminController::class);
        Route::resource('/customer', UserController::class);
        Route::prefix('produk')->group(function () {
            Route::resource('/product', ProduksController::class);
            Route::resource('/kategori', CategoriesController::class);
        });
        Route::resource('/jasa-pengiriman',JasaPengirimanController::class);
        Route::resource('/order', OrdersController::class);
        Route::resource('/company', CompanyController::class);
        Route::resource('/blog', BlogsController::class);
        Route::post('/dashboard-admin', [App\Http\Controllers\DashboardAdminController::class, 'destroyAdmin'])->name('dashboard.destroyAdmin');
        Route::resource('/voucher',VouchersController::class);
        Route::get('/page_confirm_payment/{id}',[App\Http\Controllers\OrdersController::class, 'page_confirm_payment'])->name('pageConfirmPayment');
        Route::get('/page_confirm_pengiriman/{id}',[App\Http\Controllers\OrdersController::class, 'page_confirm_pengiriman'])->name('pageConfirmPengiriman');
        Route::put('/confirm_payment/{id}',[App\Http\Controllers\OrdersController::class, 'confirm_payment'])->name('confirmPayment');
        Route::put('/confirm_pengiriman/{id}',[App\Http\Controllers\OrdersController::class, 'confirm_pengiriman'])->name('confirmPengiriman');
        Route::post('/confirm_order/{id}',[App\Http\Controllers\OrdersController::class, 'confirm_order'])->name('confirmOrder');
        Route::get('/order-export-excel', [App\Http\Controllers\OrdersController::class, 'export'])->name('orderExcel');

    });
});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::post('/register-user', [App\Http\Controllers\HomeController::class, 'registerUser'])->name('register.user');
Route::get('/profile-user', [App\Http\Controllers\HomeController::class, 'profileUser'])->name('profile.user');
Route::put('/ubah-profile/{id}', [App\Http\Controllers\HomeController::class, 'ubahProfile'])->name('ubah.profile');
Route::put('/ubah-password-user/{id}', [App\Http\Controllers\HomeController::class, 'ubahPasswordUser'])->name('ubah.passwordUser');

Route::get('/detail-order/{id}',[App\Http\Controllers\HomeController::class, 'orderDetailUser'])->name('detailOrder.edit');
Route::put('/pembayaran-order/{id}',[App\Http\Controllers\HomeController::class, 'konfirmasiOrder'])->name('detailOrder.pembayaran');

Route::get('/semua-produk', [App\Http\Controllers\HomeController::class, 'shopUser'])->name('shop.user');
Route::get('/semua-produk/{id}/{slug}', [App\Http\Controllers\HomeController::class, 'detailProduk'])->name('detail.produk');

Route::get('/get-cart', [App\Http\Controllers\HomeController::class, 'getCart'])->name('get-cart');
Route::post('/add-cart', [App\Http\Controllers\HomeController::class, 'addCart'])->name('add-cart');
Route::post('/update-cart', [App\Http\Controllers\HomeController::class, 'updateCart'])->name('update-cart');
Route::get('/detail-cart', [App\Http\Controllers\HomeController::class, 'detailCart'])->name('detail-cart');
Route::delete('/delete-cart', [App\Http\Controllers\HomeController::class, 'deleteCart'])->name('delete-cart');

Route::get('/get-voucher', [App\Http\Controllers\HomeController::class, 'getVoucher'])->name('get-voucher');

Route::post('/checkout', [App\Http\Controllers\HomeController::class, 'checkout'])->name('checkout');

Route::get('/address/user', [App\Http\Controllers\HomeController::class, 'addressUser'])->name('address.user');
Route::get('/address/user/create', [App\Http\Controllers\HomeController::class, 'addressUserCreate'])->name('address.user.create');
Route::post('/address/user/store', [App\Http\Controllers\HomeController::class, 'addressUserStore'])->name('address.user.store');
Route::get('/address/user/edit/{id}', [App\Http\Controllers\HomeController::class, 'addressUserEdit'])->name('address.user.edit');
Route::put('/address/user/update/{id}', [App\Http\Controllers\HomeController::class, 'addressUserUpdate'])->name('address.user.update');
Route::delete('/address/user/destroy/{id}', [App\Http\Controllers\HomeController::class, 'addressUserDestroy'])->name('address.user.destroy');

Route::get('/company-profile', [App\Http\Controllers\HomeController::class, 'companySetting'])->name('company-setting');
Route::get('/blog', [App\Http\Controllers\HomeController::class, 'blogSetting'])->name('blog');
Route::get('/blog-detail/{id}',[App\Http\Controllers\HomeController::class, 'blogDetail'])->name('blog-detail');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'username',
        'email',
        'password',
        'role'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function customers()
    {
        return $this->hasOne(customers::class);
    }

    public function chats()
    {
        return $this->hasMany(chats::class);
    }

    public function notifikasis()
    {
        return $this->hasMany(notifikasis::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\customers;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->search;
        $user = User::where('role', 'user')
        ->orderBy('created_at','desc');
        if (isset($search) && !empty($search)) {
            $user->where(function ($query) use ($search) {
                $query->where('username', 'like', '%' . $search . '%')
                    ->orWhere('email', 'like', '%' . $search . '%')
                        ->orWhereHas('customers', function ($query2) use ($search){
                            $query2->where('nama_lengkap', 'like', '%' . $search . '%');
                });
            });
        }
        $user = $user->paginate(7);
        return view('admin.user.index', [
            'users' => $user,
            'search' => $search
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('admin.user.edit', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validasi = Validator::make($request->all(),[
            'password' => 'confirmed'
        ]);

        if (!$validasi->fails()) {
            try {
                DB::beginTransaction();
                $user = User::find($id);
                $user->username = $request->username;
                $user->email = $request->email;
                $user->password = Hash::make($request->password);
                $user->role = 'user';
                $user->save();

                $customer = customers::where('user_id',$user->id)->first();
                $customer->nama_lengkap = $request->nama_lengkap;
                $customer->telp = $request->telp;
                $customer->tempat_lahir = $request->tempat_lahir;
                $customer->tanggal_lahir = $request->tanggal_lahir;
                if ($request->img_profile) {
                    $gambar = $this->uploadGambar($request->img_profile);
                    $customer->img_profile = $gambar;
                }
                $customer->save();

                DB::commit();
                session()->flash('success','Berhasil Mengubah Data Customer!');
                return redirect()->route('customer.index');
            } catch (\Exception $e) {
                DB::rollback();
                session()->flash('warning','Gagal Mengubah Data Customer!');
                return redirect()->back();
            }
        } else {
            session()->flash('warning','Password Yang Anda Masukkan Tidak Sama!');
            return redirect()->back();
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::destroy($id);
        return response()->json([
            'message' => 'Berhasil menghapus data customer!'
        ]);
    }
}

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    Customer
@endsection

@section('content')
  <div class="col-span-12 my-6">
    <div class="flex justify-between items-center">
        <h2 class="text-lg font-medium truncate">Ubah Data Customer</h2>
        <div class="intro-y col-span-12 flex justify-between flex-wrap sm:flex-no-wrap items-center">
            <a href="{{route('customer.index')}}" class="button w-36 mb-2 flex items-center justify-center bg-gray-700 text-white"> <i data-feather="arrow-left" class="w-4 h-4 mr-2"></i> Kembali </a>
        </div>
    </div>
  </div>
  <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
    <form action="{{ route('customer.update',$user->id) }}" method="POST" autocomplete="off" enctype="multipart/form-data">
      @method('PUT')
      @csrf
      <div class="p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
        <div class="grid grid-cols-12 gap-5">
            <div class="col-span-6">
                <div>
                    <label>Nama Lengkap</label>
                    <input type="text" name="nama_lengkap" class="input w-full border mt-2" placeholder="Masukkan nama lengkap" value="{{$user->customers->nama_lengkap}}" >
                </div>
            </div>
            <div class="col-span-6">
              <div>
                  <label>Username</label>
                  <input type="text" name="username" class="input w-full border mt-2" placeholder="Masukkan username" value="{{$user->username}}" >
              </div>
            </div>
            <div class="col-span-6">
              <div>
                  <label>No Telepon</label>
                  <input type="text" name="telp" class="input w-full border mt-2" placeholder="Masukkan no telpon" value="{{$user->customers->telp}}" >
              </div>
            </div>
            <div class="col-span-6">
              <div>
                  <label>Tempat Lahir</label>
                  <input type="text" name="tempat_lahir" class="input w-full border mt-2" placeholder="Masukkan tempat lahir" value="{{$user->customers->tempat_lahir}}" >
              </div>
            </div>
            <div class="col-span-12">
              <div>
                  <label>Tanggal Lahir</label>
                  <input type="date" name="tanggal_lahir" class="input w-full border mt-2" placeholder="Masukkan nama kategori" value="{{date('Y-m-d', strtotime($user->customers->tanggal_lahir))}}" >
              </div>
            </div>
            <div class="col-span-12">
              <div>
                  <label>Gambar</label>
                  <input type="file" name="img_profile" class="input w-full border mt-2 bg-white" placeholder="Masukkan nama kategori" value="" >
                  <div class="mt-4">
                    <a class="input-group-text button fancybox bg-theme-1 text-white" id="basic-addon2" data-caption="{{$user->username}}" href="{{asset('upload/'.$user->customers->img_profile)}}">Lihat Gambar</a>
                  </div>
              </div>
            </div>
        </div>
      </div>
      <div class="p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 my-3">
        <div class="grid grid-cols-12 gap-5">
            <div class="col-span-12">
                <div>
                    <label>Email</label>
                    <input type="text" name="email" class="input w-full border mt-2" placeholder="Masukkan nama kategori" value="{{$user->email}}" >
                </div>
            </div>
            <div class="col-span-6">
              <div>
                  <label>Password</label>
                  <input type="password" name="password" class="input w-full border mt-2" placeholder="******" value="" >
              </div>
            </div>
            <div class="col-span-6">
              <div>
                  <label>Konfirmasi Password</label>
                  <input type="password" name="password_confirmation" class="input w-full border mt-2" placeholder="******" value="" >
              </div>
            </div>
        </div>
      </div>
      <div class="col-span-12 flex justify-end" >
        <button type="submit" class="button w-36 mb-2 flex items-center justify-center bg-theme-1 text-white"> Simpan </button>
      </div>
    </form>
  </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')

@section('title')
    Customer
@endsection

@section('content')
    <div class="col-span-12 my-6">
        <div class="flex justify-content-between justify-between">
            <h2 class="text-lg font-medium truncate">Data List Customer</h2>
        </div>
        <div class="intro-y col-span-12 flex justify-between flex-wrap sm:flex-no-wrap items-center mt-2">
            <div class="w-full sm:w-auto mt-3 sm:mt-0 sm:ml-auto md:ml-0">
                <div class="w-56 relative text-gray-700">
                    <form action="" method="get" class="position-relative">
                        <input type="text" value="{{ $search }}" name="search" autocomplete="off" class="input w-56 box pr-10 placeholder-theme-13" placeholder="Search...">
                        <i class="w-4 h-4 absolute my-auto inset-y-0 mr-3 right-0" data-feather="search"></i>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- BEGIN: Data List -->
    <div class="intro-y col-span-12 overflow-auto lg:overflow-visible">
        <table class="table table-report -mt-2">
            <thead>
                <tr>
                    <th class="whitespace-no-wrap">No</th>
                    <th class="whitespace-no-wrap">Akun</th>
                    <th class="text-center whitespace-no-wrap">Aksi</th>
                </tr>
            </thead>
            <tbody>
                @if (count($users) > 0)
                    @foreach ($users as $user)
                    <tr class="intro-x">
                        <td class="w-10">{{$loop->iteration}}</td>
                        <td>
                            <a href="" class="font-medium whitespace-no-wrap">{{$user->customers->nama_lengkap}}</a>
                            <div class="text-gray-600 text-xs whitespace-no-wrap">{{$user->email}}</div>
                        </td>
                        <td class="table-report__action w-56">
                            <div class="flex justify-center items-center">
                                <a class="flex items-center mr-3" href="{{route('customer.edit',$user->id)}}"> <i data-feather="check-square" class="w-4 h-4 mr-1"></i> Edit </a>
                                <button type="button" class="flex items-center text-theme-6 delete-data" data-redirect="{{route('customer.destroy',$user->id)}}" data-id="{{ $user->id }}" data-token="{{ csrf_token() }}"> <i data-feather="trash-2" class="w-4 h-4 mr-1"></i> Hapus </button>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                @else
                    <tr>
                        <td class="intro-x text-center" colspan="5">Tidak terdapat data Customer</td>
                    </tr>
                @endif

            </tbody>
        </table>
        <div class="row">
            <div class="col-12 mt-2 mt-md-4">
                <ul class="pagination pagination_style1 justify-content-center">
                   {{ $users->links() }}
                </ul>
            </div>
        </div>
    </div>
    <!-- END: Data List -->
@endsection